//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nakazadde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<int> phone { get; set; }
        public string gender { get; set; }
        public string district { get; set; }
        public string address { get; set; }
        public Nullable<int> userid { get; set; }
        public string productName { get; set; }
        public Nullable<int> price { get; set; }
        public string paymentstatus { get; set; }
        public Nullable<System.DateTime> DateOfTransaction { get; set; }
    }
}
